### ISSUE TITLE
Common 8.60 bugs: Monster Flags, Line of Sight, Chasing delay, Pathfinding

### ISSUE THREAD

**Issue by ralke23** [nekiro/TFS-1.4-Downgrades#31] opened 2021-05-13 19:44 UTC
Hi, here is a list of common 8.60 bugs that I tested for https://otland.net/threads/8-60-otx-3-8-server-with-rebirth-loot-task-channel-autoloot-daily-tasks.274336/, still untested for this repository (TFS 1.4), but I saw the sources and should be applicable

****Protocol version**
8.60**

**Describe the bug**
a) Add new flags to monsters. Such as 		
```
<flag canwalkonenergy="0" />
<flag canwalkonfire="0" />
```
https://github.com/otland/forgottenserver/commit/0217513c0a8fa1d1dd1136cca4eb0ed72b9c28f2

b) Fix Line of Sight
https://github.com/otland/forgottenserver/pull/3265

c) Less creature delay on chasing
https://otland.net/threads/weird-monster-npc-walk-behavior.261695/#post-2531223

d) Improved monster pathfinding
https://github.com/otland/forgottenserver/pull/2464/files

****To Reproduce**
Steps to reproduce the behavior:**

Monster flags
https://www.youtube.com/watch?v=y99SCZ8XqCc

Path Finding
https://www.youtube.com/watch?v=vz6f1it64Hs

Out of sight:
https://www.youtube.com/watch?v=ob7CZ5Y0qUA

Chasing Delay
https://www.youtube.com/watch?v=sKCYpVWS9gM&t=4s

Regards!

**Comment by nekiro** [comment] 2021-05-13 19:47
Not sure what's this copypaste, but these issues are irrelevant, some of them are upstream issues and some of them are totally invalid

**Comment by EPuncker** [comment] 2021-05-13 20:05
**a)** not a bug, this fork doesn't provide a "ready to use" monster pack
**b)** line of sight as nekiro said is not related to this fork and the code you linked is not completed (as you can see the guy closed it) if we end up adding anything that were denied on upstream tfs we will end up as otservbr 🤣 
**c)** that is not the proper solution and its not advised to be used (guess why it was not added to main tfs)
**d)** just ready the comments and you will see why it was not implemented

**Closed** 2021-05-13 20:56 UTC
Labels: invalid
